"""create initial tables

Revision ID: 24b1f98ef65b
Revises: 
Create Date: 2026-08-19 03:23:15.972468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24b1f98ef65b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dam_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dam_name', sa.String(length=50), nullable=False),
    sa.Column('reading_date', sa.Date(), nullable=False),
    sa.Column('full_depth_ft', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('full_cap_mcft', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('level_ft', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('storage_mcft', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('inflow_cusecs', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('outflow_cusecs', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fill_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ttf_hours', sa.Numeric(precision=8, scale=1), nullable=True),
    sa.Column('alert_level', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dam_readings_id'), 'dam_readings', ['id'], unique=False)
    op.create_table('farmers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('village', sa.String(length=100), nullable=True),
    sa.Column('farm_size_acres', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('dam_preference', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_farmers_id'), 'farmers', ['id'], unique=False)
    op.create_table('alert_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=True),
    sa.Column('dam_name', sa.String(length=50), nullable=True),
    sa.Column('alert_level', sa.String(length=20), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('sms_status', sa.String(length=20), nullable=True),
    sa.Column('sms_provider_id', sa.String(length=100), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_logs_id'), 'alert_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_logs_id'), table_name='alert_logs')
    op.drop_table('alert_logs')
    op.drop_index(op.f('ix_farmers_id'), table_name='farmers')
    op.drop_table('farmers')
    op.drop_index(op.f('ix_dam_readings_id'), table_name='dam_readings')
    op.drop_table('dam_readings')
    # ### end Alembic commands ###
